// Generated by Sideko (sideko.dev)
use crate::schemas::*;

pub struct GetAskstoriesJsonRequest {
    pub print: Option<String>,
}

pub struct GetBeststoriesJsonRequest {
    pub print: Option<String>,
}

pub struct GetItemIdJsonRequest {
    pub id: i64,
    pub print: Option<String>,
}

pub struct GetJobstoriesJsonRequest {
    pub print: Option<String>,
}

pub struct GetMaxitemJsonRequest {
    pub print: Option<String>,
}

pub struct GetNewstoriesJsonRequest {
    pub print: Option<String>,
}

pub struct GetShowstoriesJsonRequest {
    pub print: Option<String>,
}

pub struct GetTopstoriesJsonRequest {
    pub print: Option<String>,
}

pub struct GetUpdatesJsonRequest {
    pub print: Option<String>,
}

pub struct GetUserIdJsonRequest {
    pub id: String,
    pub print: Option<String>,
}
